name: CI
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: "Deploy Website"
        steps:
            - name: Configure SSH
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/staging.key
                  chmod 600 ~/.ssh/staging.key
                  cat >>~/.ssh/config <<END
                  Host staging
                      HostName $SSH_HOST
                      User $SSH_USER
                      IdentityFile ~/.ssh/staging.key
                      StrictHostKeyChecking no
                  END
            - name: Setting Variables
              id: home
              run: echo "::set-output name=home::$(ssh staging 'cd ~ && pwd')"
            - name: Print home path
              env:
                  HOME: ${{ steps.home.outputs.home }}
              run: echo "${{ env.home }}"
