name: CI2
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        name: "Filter Config File"
        steps:
            - name: Configure SSH
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/staging.key
                  chmod 600 ~/.ssh/staging.key
                  cat >>~/.ssh/config <<END
                  Host staging
                      HostName $SSH_HOST
                      User $SSH_USER
                      IdentityFile ~/.ssh/staging.key
                      StrictHostKeyChecking no
                  END
            - name: Clone or Pull Updates
              run: |
                  ssh staging bash << EOF
                      cat ~/cremadesignstudio.com/git/config.json
                      export CONFIG=$(cat /home/callaginn/cremadesignstudio.com/git/config.json)
                      echo "CONFIG=$CONFIG" >> $GITHUB_ENV
                  EOF
            - name: Filtering Config File
              run: echo ${{ env.CONFIG }}
